import{a as v,S as w,i as m}from"./assets/vendor-D0cagnvz.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const p of r.addedNodes)p.tagName==="LINK"&&p.rel==="modulepreload"&&a(p)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const h=s=>`   
      <li class="gallery-card">
      <a class="gallery-link" href="${s.largeImageURL}"><img class="gallery-img" src="${s.webformatURL}" alt="${s.tags}" /></a>       
        <div class="gallery-info">
            <p class="info-item">Likes: <span class="span-info-item">${s.likes}</span></p>
            <p class="info-item">Views: <span class="span-info-item">${s.views}</span></p>
            <p class="info-item">Comments: <span class="span-info-item">${s.comments}</span></p>
            <p class="info-item">Downloads: <span class="span-info-item">${s.downloads}</span></p>
        </div>
      </li>
    `,y=(s,t)=>{const o={params:{key:"48309790-79d41aaa998d6ec4cf76c4434",q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15}};try{return v.get("https://pixabay.com/api/",o)}catch(a){console.log(a)}},g=document.querySelector(".loader"),u=document.querySelector(".js-search-form"),c=document.querySelector(".js-gallery"),i=document.querySelector(".js-load-more-btn");let l=1,n="";const L=()=>{g.style.display="block"},d=()=>{g.style.display="none"},S=async s=>{s.preventDefault();try{if(n=s.currentTarget.elements.user_query.value.trim(),n===""){m.error({message:"The field must be filled in!"});return}l=1,i.classList.add("is-hidden"),L();const{data:t}=await y(n,l);if(d(),console.log(n),console.log(t),t.totalHits===0){m.error({message:"Sorry, there are no images matching your search query. Please try again!"}),c.innerHTML="",u.reset();return}t.totalHits>15&&(i.classList.remove("is-hidden"),i.removeEventListener("click",f),i.addEventListener("click",f));const o=t.hits.map(a=>h(a)).join("");c.innerHTML=o,b.refresh(),u.reset()}catch(t){console.log(t),d()}};u.addEventListener("submit",S);let b=new w(".gallery-link",{captionsData:"alt",captionDelay:250});const f=async s=>{try{l++;const t=c.firstElementChild.getBoundingClientRect().height;i.classList.add("is-hidden"),L();const{data:o}=await y(n,l);d(),i.classList.remove("is-hidden");const a=o.hits.map(r=>h(r)).join("");c.insertAdjacentHTML("beforeend",a),b.refresh(),window.scrollBy({top:t*6,behavior:"smooth"});const e=Math.ceil(o.totalHits/15);l>=e&&(i.classList.add("is-hidden"),m.info({message:"We're sorry, but you've reached the end of search results."}))}catch(t){console.log(t),d()}};
//# sourceMappingURL=index.js.map
